#taps
tap "r-lib/rig"

# brews are packages
brew "bat"
brew "btop"
brew "cava"
brew "chezmoi"
brew "cowsay"
brew "duckdb"
brew "eza"
brew "fastfetch"
brew "ffmpeg"
brew "fnm"
brew "fortune"
brew "frotz"
brew "fzf"
brew "genact"
brew "gh"
brew "httpie"
brew "innoextract"
brew "lazygit"
brew "yt-dlp"
brew "mpv"
brew "pnpm"
brew "sl"
brew "starship"
brew "telnet"
brew "tldr"
brew "unar"
brew "uv"
brew "visidata"
brew "zoxide"

#casks are applications
cask "font-hack-nerd-font"
cask "font-symbols-only-nerd-font"
cask "glance-chamburr"
cask "imageoptim"
cask "jordanbaird-ice"
cask "keyboard-maestro"
cask "msty"
cask "orbstack"
cask "postman"
cask "raycast"
cask "rectangle"
cask "r-lib/rig/rig"
cask "stats"
cask "tableplus"
